Require 'List folder contents' permission to use the catalog vocabulary.
plone/plone.app.content pull request #261
Opened 2023-02-20 16:02 UTC by mauritsvanrees

This is more correct than the View permission.

2023-02-20 16:02 UTC, mister-roboto commented
@mauritsvanrees thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-02-20 16:04 UTC, mauritsvanrees commented
Let's see if Jenkins thinks this is a good idea too.

@jenkins-plone-org please run jobs

2023-02-20 17:15 UTC, jensens commented
Sounds better suited, but it may break something in heavily customized sites. The usual restrictions of the `restrictedSearch` do apply anyway, so even with `View` no harm is done IMO.

2023-04-26 06:42 UTC, ale-rt commented
I agree that `List folder contents` looks like a better fit, but:

1. I am not really sure if we want to change this in a minor release
2. I am not sure if we want to change it at all

I am +0 on merging this one now.
I would feel more confident to merge this for Plone 6.1 only, but I might be too conservative and overcautious.

2024-08-06 08:30 UTC, thet requested changes
LGTM

But I just wonder if that is a breaking change. OK, for a breaking change the effect is probably too small, but I would mention the different widgets where this change has an effect in the changelog message.

The `getVocabulary` seems to be used in:
- plone.app.content folder contents
- plone.app.querystring.
- related items widget (plone.app.z3cform.widgets.relateditems)
- link widget (plone.app.z3cform.widgets.link)
- ajax select widget (plone.app.z3cform.widgets.select)
- related items in TinyMCE (Products.CMFPlone.patterns.settings)
- TinyMCE link widget and related items widget

2024-09-24 16:50 UTC, tisto commented
@mauritsvanrees what the status of this? This PR is somehow assigned to the Plone 6.1 project. Is this correct? Do we aim to include this in Plnoe 6.1?

2024-09-24 18:14 UTC, mauritsvanrees commented
Theoretically this is better, and it gives some security hardening, but at the cost potentially breaking stuff.  I am not pursuing this currently.  I have reverted the PR to draft.

2025-02-11 22:02 UTC, mauritsvanrees commented
I am closing this.  Theoretically this change is better, but theoretically it can also break stuff.

I sometimes think of creating a `plone.hardening` package with patches like this, which can then be used on sites that are very security conscious and that are okay with possible breakage as long as it makes the site more secure.

2025-02-11 22:02 UTC, closed without merging