Fix cut / delete for content with lock created by current user
plone/plone.app.content pull request #267
Opened 2023-09-22 20:50 UTC by laulaz

This refs #266 & https://github.com/plone/Products.CMFPlone/issues/3846

2023-09-22 20:50 UTC, mister-roboto commented
@laulaz thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-09-22 20:54 UTC, laulaz commented
@jenkins-plone-org please run jobs

2023-09-25 15:09 UTC, jensens requested changes

2023-09-25 15:09 UTC, jensens commented on plone/app/content/browser/actions.py
> +            if lock_info.is_locked_for_current_user():
Isn't the logic here in the wrong direction/wrong?

2023-10-05 09:13 UTC, jensens commented on plone/app/content/browser/actions.py
> +            if lock_info.is_locked_for_current_user():
Thanks for clarification, this is indeed confusing....

2023-10-05 09:13 UTC, jensens approved these changes

2023-10-14 00:06 UTC, davisagli approved these changes
It would be nice to have a solution in Zope's functions for cutting and deleting, so that it works regardless of what UI is being used and also if a sub-item is locked. But, I acknowledge that could be complicated and this looks like a reasonable improvement.

2023-10-14 00:07 UTC, merged